Order data to match the data request
esm-tools/pymor pull request #65
Opened 2024-11-15 10:00 UTC by mandresm

# Thank you for contributing! 🎉

## Summary of the most important changes
Please summarize the most important changes you have made in this PR.

## Usage example in the PR

Please put a small usage example in the PR body so that we can see what you want to do.

You can include python:
```python
from pymorize.cmorizer import CMORizer
cmorizer = CMORizer()
cmorizer.process()
```
An example with Rules:
```python
>>> # Assume you have a Rule with these attributes:
>>> rule = Rule()
>>> rule.name = "My Rule"
>>> rule.description = "This is my rule"
>>> # Some input data
>>> data = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
>>> # Using my new step in the PR:
>>> data = my_new_step(data, rule)
>>> data
... # Add what the data should look like
```

These sorts of examples should also be in the docstrings of your code!

## Checklist
+ [ ] I have tested the changes in this PR.
+ [ ] I have updated the documentation.
+ [ ] If I have made a new step which requires new arguments, these are added to the `validate.py` file 
      so that the user can see documentation for the arguments.

## Copilot Summary
If you have Github Co-Pilot, please include an automatically generated summary.

2025-03-19 08:24 UTC, pgierz commented
@mandresm, do you want to salvage this PR, or can we close it and start a new one with the same functionality?

2025-03-24 12:48 UTC, mandresm commented
This is ready for review

2025-03-27 07:42 UTC, pgierz requested changes
I have one small idea I'd like to see added, see below. Otherwise this looks good.

2025-03-27 07:42 UTC, pgierz commented on src/pymorize/generic.py
> +    missing_dims = rule_spec.get("sort_dimensions_missing_dims", "raise")
I think we have a better way of doing this now, namely via `rule_spec._pymorize_cfg`. I think that kind of configuration is better placed there, but maybe this is something that should be specific to each rule separately, I am not sure...

2025-03-27 07:42 UTC, pgierz commented on tests/fixtures/sample_rules.py
> +        numpy.random.rand(10, 10, 10),
It might be better to put some "recognizable" numbers here in the array (at least for the time axis) and then apply the transposition. That way you can check the before and after state.

2025-03-27 07:42 UTC, pgierz commented on src/pymorize/generic.py
> +            raise ValueError("Invalid dimensions in data request variable")
I would raise a `TypeError` here, not a `ValueError`, since the checks above are determining if the array dimensions are list-ish (either as a string with split, or as a tuple/list).

```suggestion
            raise TypeError("Invalid dimensions in data request variable")
```

2025-03-27 07:42 UTC, pgierz commented on src/pymorize/generic.py
> +    data = data.transpose(*array_order, missing_dims=missing_dims)
```suggestion
    NOTE(MAM, PG): See ``missing_dims`` info here: https://tinyurl.com/mr3u9mek
    data = data.transpose(*array_order, missing_dims=missing_dims)
```

2025-03-27 07:42 UTC, pgierz commented on src/pymorize/generic.py
> +    """
```suggestion
    """
    Sorts the dimensions of a DataArray based on the array_order attribute of the
    rule_spec. If the array_order attribute is not present, it is inferred from the
    dimensions attribute of the data request variable.
    
    See Also
    --------
    * Documentation for transpose: https://tinyurl.com/mr3u9mek
    """
```

2025-05-14 13:56 UTC, pgierz commented
this passed tests now! Hooray!

2025-05-15 08:02 UTC, pgierz approved these changes

2025-05-15 08:02 UTC, merged